# common
aniso_dim: -2

arch: vqvae
optimizer: vqvae
loss: vqvae
dataset: tif_dataset
trainer: trainer

# model
in_channels: 1
out_channels: 1
features: [32,64,128]
norm_type: null
embedding_num: 64
embedding_dim: 128

# data
data: '/share/home/liuy/project/data/RESIN_datasets/NISSL/Train_datasets_2k'
data_norm_type: 'min_max'
augment: True
load_size: 64

# optimizer
lr_start: 5e-5
lr_end: 1e-7