# common
aniso_dim: -2

arch: vqvae
optimizer: vqvae
loss: vqvae
dataset: tif_dataset
trainer: trainer

# model
in_channels: 1
out_channels: 1
features: [64,128,256]
norm_type: null
embedding_num: 128
embedding_dim: 256

# data
data: '/share/home/liuy/project/data/RESIN_datasets/neuron/64_1k'
data_norm_type: 'min_max'
augment: True
load_size: 64

# optimizer
lr_start: 5e-5
lr_end: 1e-7