# common
iso_dim: -1
aniso_dim: -2
angel: -45

arch: vqvae_sr
optimizer: vqvae_sr
loss: vqvae_sr
dataset: sr_dataset
trainer: trainer_sr

# model
in_channels: 1
out_channels: 1
features: [32,64,128]
norm_type: null
embedding_num: 64
embedding_dim: 128
pretrain_ckpt: 'out/weights/vqvae_tiny/Epoch_1000.pth'

# data
data: '/share/home/liuy/project/data/RM009_ItSeg_s128/data/image'
data_norm_type: 'min_max'
augment: True
load_size: 96
feed_size: 64
full_mip: True

# loss
G_train_it: 1
D_train_it: 1

# optimizer
lr_G: 5e-5
lr_D: 5e-5
lr_end: 1e-7