# common
aniso_dim: -2

arch: vqvae_seg
optimizer: vqvae
loss: vqvae_seg
dataset: seg_dataset
trainer: trainer_seg

# model
in_channels: 1
out_channels: 1
features: [64,128,256]
norm_type: null
embedding_num: 128
embedding_dim: 256
pretrain_ckpt: 'out/weights/vqvae/Epoch_1000.pth'

# data
data: '/share/home/liuy/project/data/RM009_instance_30'
data_norm_type: 'min_max'
augment: True
load_size: 64

# optimizer
lr_start: 1e-4
lr_end: 1e-7