# common
arch: vqvae_2d
optimizer: vqvae
loss: vqvae_2d
dataset: npz_dataset
trainer: trainer

# model
in_channels: 1
out_channels: 1
features: [64,128,256]
norm_type: null
embedding_num: 128
embedding_dim: 256

# data
data: '/share/home/liuy/project/data/CARE/Isotropic_Liver/train_data/data_label.npz'
data_norm_type: 'min_max'
load_size: 64

# optimizer
lr_start: 5e-5
lr_end: 1e-7